#Use the new container-based infrastructure
sudo: false
language: c++
cache:
  directories:
    - .tmp

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6

#Webhooks
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c566d34b63ca82e43bbb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

#Set the build environment
env:
  global:
    - secure: "KYpwJLE/aquoy9pnPSdgYECy1G8t5AO1RRqNaJjqwLAhjoge5nHRzhZnEhcOC+8wi+dfXUr+Dp4OA8k1ZZVykNGc+HNLTF0COj4FVsSG+JogVGCIr0I0o/7NnxiTgRQ08jugNCIGYNtQhgY4F+FYz03DY93XwO0tNM8JjNM+8NBegYR9t/pdZv9iQHSz74AeFMfC1//7ZyP9CnjY40HIa76e7evqmkE1A0kzBnjQfpgK3bBYddDaowC3zh7J36iw7QOawe3MqhmtNGodjH/AjPFsCsr+xC8zqMiQURBw3e08x7d50FWI4+XAmxeW6E2WrB+RS1Q8j7+ot0tvNfOhpQLpOhr/xpsRTYEyj/o/OvPtDHlEpnkm1zKaEJojHLnVJVLy4ktnZbDslPnkrQezhMqFc4wazUkZgFX7ZovuZUr67RYX02buLcndkqdDhQL6EuqLRLElKfP3vIsn/dqNN3OMefMz/BORDwPOuvbXaG6JynFx2mCov3pRXe4Y+IIFgbxRoGDu0OjdF+BCXGaqvanYu+Fw5iSBJndFjMPZubexJF6z+4RkFR6B5SWCV1YbJn3W2ilyK2e6gvrme63MCvQGVuzqSIqKKSSRWkhHdzVNHD2sLJKkQ8n4C6byaUdWwiZhI9O6+r1vUE6fw+GTDcMQLjhS6KIIEFJtxNCbk2E="
  matrix:
    - SOURCEMOD=stable
    - SOURCEMOD=dev
    
matrix:
  # Mark build as finished as soon as stable compilation is completed
  fast_finish: true
  # Allow dev build to fail
  allow_failures:
    - env: SOURCEMOD=dev

git:
  depth: 9999999


#And compile!
script:
  - make build-$SOURCEMOD

deploy:
  # don't remove files generated during the "build" task
  skip_cleanup: true
  # use custom shell scripting to deploy (we deploy to `build` branch)
  provider: script
  script: echo "DEPLOYING :)"
  # only run this when master branch is modified
  on:
    branch: master
